#!/usr/bin/env ruby
#Load Library
require 'lib/bot-config'		#Bot Settings
require 'lib/irc-connect'		#IRC Socket
require 'lib/string-methods'		#String Methods "string".privmsg? etc...
require 'lib/command-startup.rb'	#Command Loader
require 'lib/datastore.rb'		#Datastore Manager
require 'lib/database.rb'		#Database


#Display a start message
puts "**********************************************************"
puts "Starting RIRCB"
puts "**********************************************************"

#A brief pause
sleep 1

#Load Config
puts "Loading Config"
bot=Bot.new(IRC.new)

#A brief pause
sleep 1

#The All important loop
puts "**********************************************************"
puts "Starting the Main process loop"
puts "**********************************************************"

#A brief pause
sleep 1

while (bot.reboot? != true && bot.kill? != true)
	bot.run
end

bot.disconnect

if bot.reboot?
	sleep 5 #Just need to let the Past instance clear
	exec "./script/run"
end
